<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\CompetitionController;
use App\Http\Controllers\Admin\FixtureController;
use App\Http\Controllers\Admin\TeamController;
use App\Http\Controllers\Admin\GameRuleController;
use App\Http\Controllers\Admin\ImportController;
use App\Http\Controllers\Admin\DashboardController as AdminDashboard;

use App\Http\Controllers\TeamPickerController;
use Inertia\Inertia;

Route::get('/', function () {
    return Inertia::render('welcome');
})->name('home');

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('dashboard', function () {
        return Inertia::render('dashboard');
    })->name('dashboard');

    Route::get('team-picker', [TeamPickerController::class, 'index']);
});


// admin routes
Route::prefix('admin')
    ->name('admin.')
    ->middleware(['auth'])
    ->group(function () {
        Route::resource('settings/rules', GameRuleController::class);
        Route::resource('competitions', CompetitionController::class);
        Route::resource('fixtures', FixtureController::class);
        Route::resource('teams', TeamController::class);
        Route::get('/import', [ImportController::class, 'index'])->name('imports.index');
        Route::post('/import', [ImportController::class, 'submit'])->name('imports.submit');
        Route::get('/', [AdminDashboard::class, 'index'])->name('dashboard');
    });

require __DIR__.'/settings.php';
require __DIR__.'/auth.php';


Route::get('/update-fixtures', function () {


$fixtures = [
['id' => 1, 'home_team_id' => 1, 'away_team_id' => 4],
['id' => 2, 'home_team_id' => 20, 'away_team_id' => 6],
['id' => 3, 'home_team_id' => 8, 'away_team_id' => 5],
['id' => 4, 'home_team_id' => 9, 'away_team_id' => 15],
['id' => 5, 'home_team_id' => 2, 'away_team_id' => 7],
['id' => 6, 'home_team_id' => 18, 'away_team_id' => 3],
['id' => 7, 'home_team_id' => 12, 'away_team_id' => 19],
['id' => 8, 'home_team_id' => 17, 'away_team_id' => 16],
['id' => 9, 'home_team_id' => 13, 'away_team_id' => 14],
['id' => 10, 'home_team_id' => 10, 'away_team_id' => 11],
['id' => 11, 'home_team_id' => 15, 'away_team_id' => 1],
['id' => 12, 'home_team_id' => 16, 'away_team_id' => 12],
['id' => 13, 'home_team_id' => 4, 'away_team_id' => 10],
['id' => 14, 'home_team_id' => 14, 'away_team_id' => 20],
['id' => 15, 'home_team_id' => 7, 'away_team_id' => 18],
['id' => 16, 'home_team_id' => 11, 'away_team_id' => 9],
['id' => 17, 'home_team_id' => 19, 'away_team_id' => 8],
['id' => 18, 'home_team_id' => 3, 'away_team_id' => 2],
['id' => 19, 'home_team_id' => 5, 'away_team_id' => 13],
['id' => 20, 'home_team_id' => 6, 'away_team_id' => 17],
['id' => 21, 'home_team_id' => 8, 'away_team_id' => 15],
['id' => 22, 'home_team_id' => 17, 'away_team_id' => 7],
['id' => 23, 'home_team_id' => 9, 'away_team_id' => 3],
['id' => 24, 'home_team_id' => 20, 'away_team_id' => 4],
['id' => 25, 'home_team_id' => 10, 'away_team_id' => 19],
['id' => 26, 'home_team_id' => 18, 'away_team_id' => 5],
['id' => 27, 'home_team_id' => 12, 'away_team_id' => 14],
['id' => 28, 'home_team_id' => 13, 'away_team_id' => 16],
['id' => 29, 'home_team_id' => 2, 'away_team_id' => 11],
['id' => 30, 'home_team_id' => 1, 'away_team_id' => 6],
['id' => 31, 'home_team_id' => 7, 'away_team_id' => 1],
['id' => 32, 'home_team_id' => 15, 'away_team_id' => 20],
['id' => 33, 'home_team_id' => 16, 'away_team_id' => 10],
['id' => 34, 'home_team_id' => 4, 'away_team_id' => 12],
['id' => 35, 'home_team_id' => 6, 'away_team_id' => 18],
['id' => 36, 'home_team_id' => 14, 'away_team_id' => 17],
['id' => 37, 'home_team_id' => 19, 'away_team_id' => 9],
['id' => 38, 'home_team_id' => 3, 'away_team_id' => 13],
['id' => 39, 'home_team_id' => 11, 'away_team_id' => 8],
['id' => 40, 'home_team_id' => 5, 'away_team_id' => 2],
['id' => 41, 'home_team_id' => 12, 'away_team_id' => 13],
['id' => 42, 'home_team_id' => 19, 'away_team_id' => 5],
['id' => 43, 'home_team_id' => 4, 'away_team_id' => 2],
['id' => 44, 'home_team_id' => 10, 'away_team_id' => 9],
['id' => 45, 'home_team_id' => 6, 'away_team_id' => 3],
['id' => 46, 'home_team_id' => 7, 'away_team_id' => 20],
['id' => 47, 'home_team_id' => 11, 'away_team_id' => 17],
['id' => 48, 'home_team_id' => 16, 'away_team_id' => 1],
['id' => 49, 'home_team_id' => 15, 'away_team_id' => 18],
['id' => 50, 'home_team_id' => 14, 'away_team_id' => 8],
['id' => 51, 'home_team_id' => 2, 'away_team_id' => 14],
['id' => 52, 'home_team_id' => 8, 'away_team_id' => 10],
['id' => 53, 'home_team_id' => 17, 'away_team_id' => 12],
['id' => 54, 'home_team_id' => 13, 'away_team_id' => 15],
['id' => 55, 'home_team_id' => 9, 'away_team_id' => 16],
['id' => 56, 'home_team_id' => 18, 'away_team_id' => 4],
['id' => 57, 'home_team_id' => 5, 'away_team_id' => 6],
['id' => 58, 'home_team_id' => 20, 'away_team_id' => 19],
['id' => 59, 'home_team_id' => 1, 'away_team_id' => 11],
['id' => 60, 'home_team_id' => 3, 'away_team_id' => 7],
['id' => 61, 'home_team_id' => 16, 'away_team_id' => 6],
['id' => 62, 'home_team_id' => 8, 'away_team_id' => 7],
['id' => 63, 'home_team_id' => 17, 'away_team_id' => 5],
['id' => 64, 'home_team_id' => 10, 'away_team_id' => 3],
['id' => 65, 'home_team_id' => 14, 'away_team_id' => 4],
['id' => 66, 'home_team_id' => 12, 'away_team_id' => 20],
['id' => 67, 'home_team_id' => 9, 'away_team_id' => 2],
['id' => 68, 'home_team_id' => 19, 'away_team_id' => 1],
['id' => 69, 'home_team_id' => 13, 'away_team_id' => 18],
['id' => 70, 'home_team_id' => 15, 'away_team_id' => 11],
['id' => 71, 'home_team_id' => 11, 'away_team_id' => 12],
['id' => 72, 'home_team_id' => 4, 'away_team_id' => 19],
['id' => 73, 'home_team_id' => 1, 'away_team_id' => 17],
['id' => 74, 'home_team_id' => 2, 'away_team_id' => 15],
['id' => 75, 'home_team_id' => 7, 'away_team_id' => 10],
['id' => 76, 'home_team_id' => 20, 'away_team_id' => 9],
['id' => 77, 'home_team_id' => 3, 'away_team_id' => 8],
['id' => 78, 'home_team_id' => 5, 'away_team_id' => 14],
['id' => 79, 'home_team_id' => 6, 'away_team_id' => 13],
['id' => 80, 'home_team_id' => 18, 'away_team_id' => 16],
['id' => 81, 'home_team_id' => 10, 'away_team_id' => 18],
['id' => 82, 'home_team_id' => 19, 'away_team_id' => 3],
['id' => 83, 'home_team_id' => 17, 'away_team_id' => 20],
['id' => 84, 'home_team_id' => 15, 'away_team_id' => 5],
['id' => 85, 'home_team_id' => 14, 'away_team_id' => 7],
['id' => 86, 'home_team_id' => 9, 'away_team_id' => 4],
['id' => 87, 'home_team_id' => 13, 'away_team_id' => 2],
['id' => 88, 'home_team_id' => 16, 'away_team_id' => 11],
['id' => 89, 'home_team_id' => 12, 'away_team_id' => 1],
['id' => 90, 'home_team_id' => 8, 'away_team_id' => 6],
['id' => 91, 'home_team_id' => 2, 'away_team_id' => 8],
['id' => 92, 'home_team_id' => 3, 'away_team_id' => 14],
['id' => 93, 'home_team_id' => 20, 'away_team_id' => 10],
['id' => 94, 'home_team_id' => 6, 'away_team_id' => 15],
['id' => 95, 'home_team_id' => 18, 'away_team_id' => 12],
['id' => 96, 'home_team_id' => 7, 'away_team_id' => 9],
['id' => 97, 'home_team_id' => 5, 'away_team_id' => 16],
['id' => 98, 'home_team_id' => 11, 'away_team_id' => 19],
['id' => 99, 'home_team_id' => 1, 'away_team_id' => 13],
['id' => 100, 'home_team_id' => 4, 'away_team_id' => 17],
['id' => 101, 'home_team_id' => 17, 'away_team_id' => 3],
['id' => 102, 'home_team_id' => 16, 'away_team_id' => 4],
['id' => 103, 'home_team_id' => 12, 'away_team_id' => 9],
['id' => 104, 'home_team_id' => 5, 'away_team_id' => 7],
['id' => 105, 'home_team_id' => 15, 'away_team_id' => 14],
['id' => 106, 'home_team_id' => 6, 'away_team_id' => 19],
['id' => 107, 'home_team_id' => 1, 'away_team_id' => 10],
['id' => 108, 'home_team_id' => 18, 'away_team_id' => 2],
['id' => 109, 'home_team_id' => 11, 'away_team_id' => 20],
['id' => 110, 'home_team_id' => 13, 'away_team_id' => 8],
['id' => 111, 'home_team_id' => 10, 'away_team_id' => 13],
['id' => 112, 'home_team_id' => 8, 'away_team_id' => 18],
['id' => 113, 'home_team_id' => 19, 'away_team_id' => 16],
['id' => 114, 'home_team_id' => 3, 'away_team_id' => 15],
['id' => 115, 'home_team_id' => 9, 'away_team_id' => 17],
['id' => 116, 'home_team_id' => 4, 'away_team_id' => 5],
['id' => 117, 'home_team_id' => 14, 'away_team_id' => 11],
['id' => 118, 'home_team_id' => 7, 'away_team_id' => 6],
['id' => 119, 'home_team_id' => 20, 'away_team_id' => 1],
['id' => 120, 'home_team_id' => 2, 'away_team_id' => 12],
['id' => 121, 'home_team_id' => 15, 'away_team_id' => 7],
['id' => 122, 'home_team_id' => 17, 'away_team_id' => 10],
['id' => 123, 'home_team_id' => 16, 'away_team_id' => 2],
['id' => 124, 'home_team_id' => 18, 'away_team_id' => 20],
['id' => 125, 'home_team_id' => 5, 'away_team_id' => 3],
['id' => 126, 'home_team_id' => 12, 'away_team_id' => 8],
['id' => 127, 'home_team_id' => 13, 'away_team_id' => 19],
['id' => 128, 'home_team_id' => 1, 'away_team_id' => 9],
['id' => 129, 'home_team_id' => 11, 'away_team_id' => 4],
['id' => 130, 'home_team_id' => 6, 'away_team_id' => 14],
['id' => 131, 'home_team_id' => 20, 'away_team_id' => 16],
['id' => 132, 'home_team_id' => 10, 'away_team_id' => 12],
['id' => 133, 'home_team_id' => 9, 'away_team_id' => 5],
['id' => 134, 'home_team_id' => 14, 'away_team_id' => 18],
['id' => 135, 'home_team_id' => 2, 'away_team_id' => 6],
['id' => 136, 'home_team_id' => 7, 'away_team_id' => 13],
['id' => 137, 'home_team_id' => 8, 'away_team_id' => 1],
['id' => 138, 'home_team_id' => 19, 'away_team_id' => 17],
['id' => 139, 'home_team_id' => 4, 'away_team_id' => 15],
['id' => 140, 'home_team_id' => 3, 'away_team_id' => 11],
['id' => 141, 'home_team_id' => 19, 'away_team_id' => 7],
['id' => 142, 'home_team_id' => 17, 'away_team_id' => 2],
['id' => 143, 'home_team_id' => 16, 'away_team_id' => 14],
['id' => 144, 'home_team_id' => 1, 'away_team_id' => 18],
['id' => 145, 'home_team_id' => 4, 'away_team_id' => 8],
['id' => 146, 'home_team_id' => 20, 'away_team_id' => 3],
['id' => 147, 'home_team_id' => 10, 'away_team_id' => 15],
['id' => 148, 'home_team_id' => 11, 'away_team_id' => 13],
['id' => 149, 'home_team_id' => 12, 'away_team_id' => 5],
['id' => 150, 'home_team_id' => 9, 'away_team_id' => 6],
['id' => 151, 'home_team_id' => 8, 'away_team_id' => 9],
['id' => 152, 'home_team_id' => 6, 'away_team_id' => 4],
['id' => 153, 'home_team_id' => 2, 'away_team_id' => 10],
['id' => 154, 'home_team_id' => 5, 'away_team_id' => 20],
['id' => 155, 'home_team_id' => 18, 'away_team_id' => 19],
['id' => 156, 'home_team_id' => 15, 'away_team_id' => 16],
['id' => 157, 'home_team_id' => 14, 'away_team_id' => 1],
['id' => 158, 'home_team_id' => 13, 'away_team_id' => 17],
['id' => 159, 'home_team_id' => 7, 'away_team_id' => 11],
['id' => 160, 'home_team_id' => 3, 'away_team_id' => 12],
['id' => 161, 'home_team_id' => 19, 'away_team_id' => 14],
['id' => 162, 'home_team_id' => 17, 'away_team_id' => 18],
['id' => 163, 'home_team_id' => 20, 'away_team_id' => 2],
['id' => 164, 'home_team_id' => 12, 'away_team_id' => 15],
['id' => 165, 'home_team_id' => 16, 'away_team_id' => 8],
['id' => 166, 'home_team_id' => 9, 'away_team_id' => 13],
['id' => 167, 'home_team_id' => 4, 'away_team_id' => 7],
['id' => 168, 'home_team_id' => 10, 'away_team_id' => 5],
['id' => 169, 'home_team_id' => 1, 'away_team_id' => 3],
['id' => 170, 'home_team_id' => 11, 'away_team_id' => 6],
['id' => 171, 'home_team_id' => 14, 'away_team_id' => 9],
['id' => 172, 'home_team_id' => 3, 'away_team_id' => 16],
['id' => 173, 'home_team_id' => 13, 'away_team_id' => 4],
['id' => 174, 'home_team_id' => 2, 'away_team_id' => 19],
['id' => 175, 'home_team_id' => 18, 'away_team_id' => 11],
['id' => 176, 'home_team_id' => 7, 'away_team_id' => 12],
['id' => 177, 'home_team_id' => 5, 'away_team_id' => 1],
['id' => 178, 'home_team_id' => 6, 'away_team_id' => 10],
['id' => 179, 'home_team_id' => 15, 'away_team_id' => 17],
['id' => 180, 'home_team_id' => 8, 'away_team_id' => 20],
['id' => 181, 'home_team_id' => 10, 'away_team_id' => 14],
['id' => 182, 'home_team_id' => 16, 'away_team_id' => 7],
['id' => 183, 'home_team_id' => 9, 'away_team_id' => 18],
['id' => 184, 'home_team_id' => 4, 'away_team_id' => 3],
['id' => 185, 'home_team_id' => 11, 'away_team_id' => 5],
['id' => 186, 'home_team_id' => 12, 'away_team_id' => 6],
['id' => 187, 'home_team_id' => 19, 'away_team_id' => 15],
['id' => 188, 'home_team_id' => 20, 'away_team_id' => 13],
['id' => 189, 'home_team_id' => 1, 'away_team_id' => 2],
['id' => 190, 'home_team_id' => 17, 'away_team_id' => 8],
['id' => 191, 'home_team_id' => 11, 'away_team_id' => 2],
['id' => 192, 'home_team_id' => 19, 'away_team_id' => 10],
['id' => 193, 'home_team_id' => 3, 'away_team_id' => 9],
['id' => 194, 'home_team_id' => 16, 'away_team_id' => 13],
['id' => 195, 'home_team_id' => 14, 'away_team_id' => 12],
['id' => 196, 'home_team_id' => 7, 'away_team_id' => 17],
['id' => 197, 'home_team_id' => 15, 'away_team_id' => 8],
['id' => 198, 'home_team_id' => 4, 'away_team_id' => 20],
['id' => 199, 'home_team_id' => 6, 'away_team_id' => 1],
['id' => 200, 'home_team_id' => 5, 'away_team_id' => 18],
['id' => 201, 'home_team_id' => 17, 'away_team_id' => 14],
['id' => 202, 'home_team_id' => 12, 'away_team_id' => 4],
['id' => 203, 'home_team_id' => 13, 'away_team_id' => 3],
['id' => 204, 'home_team_id' => 18, 'away_team_id' => 6],
['id' => 205, 'home_team_id' => 9, 'away_team_id' => 19],
['id' => 206, 'home_team_id' => 10, 'away_team_id' => 16],
['id' => 207, 'home_team_id' => 2, 'away_team_id' => 5],
['id' => 208, 'home_team_id' => 8, 'away_team_id' => 11],
['id' => 209, 'home_team_id' => 20, 'away_team_id' => 15],
['id' => 210, 'home_team_id' => 1, 'away_team_id' => 7],
['id' => 211, 'home_team_id' => 2, 'away_team_id' => 3],
['id' => 212, 'home_team_id' => 17, 'away_team_id' => 6],
['id' => 213, 'home_team_id' => 10, 'away_team_id' => 4],
['id' => 214, 'home_team_id' => 12, 'away_team_id' => 16],
['id' => 215, 'home_team_id' => 8, 'away_team_id' => 19],
['id' => 216, 'home_team_id' => 9, 'away_team_id' => 11],
['id' => 217, 'home_team_id' => 1, 'away_team_id' => 15],
['id' => 218, 'home_team_id' => 18, 'away_team_id' => 7],
['id' => 219, 'home_team_id' => 20, 'away_team_id' => 14],
['id' => 220, 'home_team_id' => 13, 'away_team_id' => 5],
['id' => 221, 'home_team_id' => 3, 'away_team_id' => 18],
['id' => 222, 'home_team_id' => 15, 'away_team_id' => 9],
['id' => 223, 'home_team_id' => 6, 'away_team_id' => 20],
['id' => 224, 'home_team_id' => 7, 'away_team_id' => 2],
['id' => 225, 'home_team_id' => 5, 'away_team_id' => 8],
['id' => 226, 'home_team_id' => 14, 'away_team_id' => 13],
['id' => 227, 'home_team_id' => 16, 'away_team_id' => 17],
['id' => 228, 'home_team_id' => 11, 'away_team_id' => 10],
['id' => 229, 'home_team_id' => 19, 'away_team_id' => 12],
['id' => 230, 'home_team_id' => 4, 'away_team_id' => 1],
['id' => 231, 'home_team_id' => 18, 'away_team_id' => 15],
['id' => 232, 'home_team_id' => 3, 'away_team_id' => 6],
['id' => 233, 'home_team_id' => 9, 'away_team_id' => 10],
['id' => 234, 'home_team_id' => 20, 'away_team_id' => 7],
['id' => 235, 'home_team_id' => 2, 'away_team_id' => 4],
['id' => 236, 'home_team_id' => 5, 'away_team_id' => 19],
['id' => 237, 'home_team_id' => 17, 'away_team_id' => 11],
['id' => 238, 'home_team_id' => 1, 'away_team_id' => 16],
['id' => 239, 'home_team_id' => 8, 'away_team_id' => 14],
['id' => 240, 'home_team_id' => 13, 'away_team_id' => 12],
['id' => 241, 'home_team_id' => 15, 'away_team_id' => 13],
['id' => 242, 'home_team_id' => 10, 'away_team_id' => 8],
['id' => 243, 'home_team_id' => 19, 'away_team_id' => 20],
['id' => 244, 'home_team_id' => 4, 'away_team_id' => 18],
['id' => 245, 'home_team_id' => 14, 'away_team_id' => 2],
['id' => 246, 'home_team_id' => 7, 'away_team_id' => 3],
['id' => 247, 'home_team_id' => 12, 'away_team_id' => 17],
['id' => 248, 'home_team_id' => 16, 'away_team_id' => 9],
['id' => 249, 'home_team_id' => 6, 'away_team_id' => 5],
['id' => 250, 'home_team_id' => 11, 'away_team_id' => 1],
['id' => 251, 'home_team_id' => 10, 'away_team_id' => 17],
['id' => 252, 'home_team_id' => 9, 'away_team_id' => 1],
['id' => 253, 'home_team_id' => 8, 'away_team_id' => 12],
['id' => 254, 'home_team_id' => 3, 'away_team_id' => 5],
['id' => 255, 'home_team_id' => 4, 'away_team_id' => 16],
['id' => 256, 'home_team_id' => 20, 'away_team_id' => 11],
['id' => 257, 'home_team_id' => 7, 'away_team_id' => 15],
['id' => 258, 'home_team_id' => 19, 'away_team_id' => 13],
['id' => 259, 'home_team_id' => 2, 'away_team_id' => 18],
['id' => 260, 'home_team_id' => 14, 'away_team_id' => 6],
['id' => 261, 'home_team_id' => 15, 'away_team_id' => 3],
['id' => 262, 'home_team_id' => 5, 'away_team_id' => 4],
['id' => 263, 'home_team_id' => 16, 'away_team_id' => 19],
['id' => 264, 'home_team_id' => 13, 'away_team_id' => 7],
['id' => 265, 'home_team_id' => 17, 'away_team_id' => 9],
['id' => 266, 'home_team_id' => 18, 'away_team_id' => 8],
['id' => 267, 'home_team_id' => 11, 'away_team_id' => 14],
['id' => 268, 'home_team_id' => 1, 'away_team_id' => 20],
['id' => 269, 'home_team_id' => 6, 'away_team_id' => 2],
['id' => 270, 'home_team_id' => 12, 'away_team_id' => 10],
['id' => 271, 'home_team_id' => 18, 'away_team_id' => 14],
['id' => 272, 'home_team_id' => 15, 'away_team_id' => 4],
['id' => 273, 'home_team_id' => 16, 'away_team_id' => 20],
['id' => 274, 'home_team_id' => 6, 'away_team_id' => 7],
['id' => 275, 'home_team_id' => 17, 'away_team_id' => 19],
['id' => 276, 'home_team_id' => 5, 'away_team_id' => 9],
['id' => 277, 'home_team_id' => 13, 'away_team_id' => 10],
['id' => 278, 'home_team_id' => 11, 'away_team_id' => 3],
['id' => 279, 'home_team_id' => 1, 'away_team_id' => 8],
['id' => 280, 'home_team_id' => 12, 'away_team_id' => 2],
['id' => 281, 'home_team_id' => 19, 'away_team_id' => 6],
['id' => 282, 'home_team_id' => 9, 'away_team_id' => 12],
['id' => 283, 'home_team_id' => 20, 'away_team_id' => 18],
['id' => 284, 'home_team_id' => 14, 'away_team_id' => 15],
['id' => 285, 'home_team_id' => 7, 'away_team_id' => 5],
['id' => 286, 'home_team_id' => 3, 'away_team_id' => 17],
['id' => 287, 'home_team_id' => 8, 'away_team_id' => 13],
['id' => 288, 'home_team_id' => 4, 'away_team_id' => 11],
['id' => 289, 'home_team_id' => 10, 'away_team_id' => 1],
['id' => 290, 'home_team_id' => 2, 'away_team_id' => 16],
['id' => 291, 'home_team_id' => 8, 'away_team_id' => 4],
['id' => 292, 'home_team_id' => 5, 'away_team_id' => 12],
['id' => 293, 'home_team_id' => 18, 'away_team_id' => 1],
['id' => 294, 'home_team_id' => 3, 'away_team_id' => 20],
['id' => 295, 'home_team_id' => 15, 'away_team_id' => 19],
['id' => 296, 'home_team_id' => 14, 'away_team_id' => 10],
['id' => 297, 'home_team_id' => 2, 'away_team_id' => 17],
['id' => 298, 'home_team_id' => 7, 'away_team_id' => 16],
['id' => 299, 'home_team_id' => 6, 'away_team_id' => 9],
['id' => 300, 'home_team_id' => 13, 'away_team_id' => 11],
['id' => 301, 'home_team_id' => 9, 'away_team_id' => 8],
['id' => 302, 'home_team_id' => 16, 'away_team_id' => 15],
['id' => 303, 'home_team_id' => 20, 'away_team_id' => 5],
['id' => 304, 'home_team_id' => 12, 'away_team_id' => 3],
['id' => 305, 'home_team_id' => 19, 'away_team_id' => 18],
['id' => 306, 'home_team_id' => 17, 'away_team_id' => 13],
['id' => 307, 'home_team_id' => 4, 'away_team_id' => 6],
['id' => 308, 'home_team_id' => 11, 'away_team_id' => 7],
['id' => 309, 'home_team_id' => 1, 'away_team_id' => 14],
['id' => 310, 'home_team_id' => 10, 'away_team_id' => 2],
['id' => 311, 'home_team_id' => 14, 'away_team_id' => 16],
['id' => 312, 'home_team_id' => 15, 'away_team_id' => 10],
['id' => 313, 'home_team_id' => 18, 'away_team_id' => 9],
['id' => 314, 'home_team_id' => 7, 'away_team_id' => 19],
['id' => 315, 'home_team_id' => 8, 'away_team_id' => 17],
['id' => 316, 'home_team_id' => 13, 'away_team_id' => 20],
['id' => 317, 'home_team_id' => 6, 'away_team_id' => 12],
['id' => 318, 'home_team_id' => 5, 'away_team_id' => 11],
['id' => 319, 'home_team_id' => 2, 'away_team_id' => 1],
['id' => 320, 'home_team_id' => 3, 'away_team_id' => 4],
['id' => 321, 'home_team_id' => 17, 'away_team_id' => 15],
['id' => 322, 'home_team_id' => 16, 'away_team_id' => 3],
['id' => 323, 'home_team_id' => 9, 'away_team_id' => 14],
['id' => 324, 'home_team_id' => 12, 'away_team_id' => 7],
['id' => 325, 'home_team_id' => 19, 'away_team_id' => 2],
['id' => 326, 'home_team_id' => 4, 'away_team_id' => 13],
['id' => 327, 'home_team_id' => 20, 'away_team_id' => 8],
['id' => 328, 'home_team_id' => 1, 'away_team_id' => 5],
['id' => 329, 'home_team_id' => 10, 'away_team_id' => 6],
['id' => 330, 'home_team_id' => 11, 'away_team_id' => 18],
['id' => 331, 'home_team_id' => 14, 'away_team_id' => 19],
['id' => 332, 'home_team_id' => 8, 'away_team_id' => 16],
['id' => 333, 'home_team_id' => 13, 'away_team_id' => 9],
['id' => 334, 'home_team_id' => 15, 'away_team_id' => 12],
['id' => 335, 'home_team_id' => 2, 'away_team_id' => 20],
['id' => 336, 'home_team_id' => 7, 'away_team_id' => 4],
['id' => 337, 'home_team_id' => 5, 'away_team_id' => 10],
['id' => 338, 'home_team_id' => 3, 'away_team_id' => 1],
['id' => 339, 'home_team_id' => 6, 'away_team_id' => 11],
['id' => 340, 'home_team_id' => 18, 'away_team_id' => 17],
['id' => 341, 'home_team_id' => 14, 'away_team_id' => 5],
['id' => 342, 'home_team_id' => 19, 'away_team_id' => 4],
['id' => 343, 'home_team_id' => 9, 'away_team_id' => 20],
['id' => 344, 'home_team_id' => 10, 'away_team_id' => 7],
['id' => 345, 'home_team_id' => 8, 'away_team_id' => 3],
['id' => 346, 'home_team_id' => 17, 'away_team_id' => 1],
['id' => 347, 'home_team_id' => 15, 'away_team_id' => 2],
['id' => 348, 'home_team_id' => 12, 'away_team_id' => 11],
['id' => 349, 'home_team_id' => 13, 'away_team_id' => 6],
['id' => 350, 'home_team_id' => 16, 'away_team_id' => 18],
['id' => 351, 'home_team_id' => 4, 'away_team_id' => 9],
['id' => 352, 'home_team_id' => 20, 'away_team_id' => 17],
['id' => 353, 'home_team_id' => 7, 'away_team_id' => 14],
['id' => 354, 'home_team_id' => 5, 'away_team_id' => 15],
['id' => 355, 'home_team_id' => 3, 'away_team_id' => 19],
['id' => 356, 'home_team_id' => 2, 'away_team_id' => 13],
['id' => 357, 'home_team_id' => 1, 'away_team_id' => 12],
['id' => 358, 'home_team_id' => 18, 'away_team_id' => 10],
['id' => 359, 'home_team_id' => 11, 'away_team_id' => 16],
['id' => 360, 'home_team_id' => 6, 'away_team_id' => 8],
['id' => 361, 'home_team_id' => 19, 'away_team_id' => 11],
['id' => 362, 'home_team_id' => 13, 'away_team_id' => 1],
['id' => 363, 'home_team_id' => 9, 'away_team_id' => 7],
['id' => 364, 'home_team_id' => 12, 'away_team_id' => 18],
['id' => 365, 'home_team_id' => 17, 'away_team_id' => 4],
['id' => 366, 'home_team_id' => 10, 'away_team_id' => 20],
['id' => 367, 'home_team_id' => 8, 'away_team_id' => 2],
['id' => 368, 'home_team_id' => 15, 'away_team_id' => 6],
['id' => 369, 'home_team_id' => 16, 'away_team_id' => 5],
['id' => 370, 'home_team_id' => 14, 'away_team_id' => 3],
['id' => 371, 'home_team_id' => 3, 'away_team_id' => 10],
['id' => 372, 'home_team_id' => 4, 'away_team_id' => 14],
['id' => 373, 'home_team_id' => 20, 'away_team_id' => 12],
['id' => 374, 'home_team_id' => 6, 'away_team_id' => 16],
['id' => 375, 'home_team_id' => 1, 'away_team_id' => 19],
['id' => 376, 'home_team_id' => 2, 'away_team_id' => 9],
['id' => 377, 'home_team_id' => 18, 'away_team_id' => 13],
['id' => 378, 'home_team_id' => 7, 'away_team_id' => 8],
['id' => 379, 'home_team_id' => 11, 'away_team_id' => 15],
['id' => 380, 'home_team_id' => 5, 'away_team_id' => 17],
];

$results = array(
    array('id'=>"1", 'home_team_score'=>"1", 'away_team_score'=>"0"),
    array('id'=>"2", 'home_team_score'=>"0", 'away_team_score'=>"2"),
    array('id'=>"3", 'home_team_score'=>"2", 'away_team_score'=>"0"),
    array('id'=>"4", 'home_team_score'=>"0", 'away_team_score'=>"3"),
    array('id'=>"5", 'home_team_score'=>"1", 'away_team_score'=>"0"),
    array('id'=>"6", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"7", 'home_team_score'=>"1", 'away_team_score'=>"2"),
    array('id'=>"8", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"9", 'home_team_score'=>"0", 'away_team_score'=>"2"),
    array('id'=>"10", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"11", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"12", 'home_team_score'=>"0", 'away_team_score'=>"2"),
    array('id'=>"13", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"14", 'home_team_score'=>"4", 'away_team_score'=>"1"),
    array('id'=>"15", 'home_team_score'=>"0", 'away_team_score'=>"1"),
    array('id'=>"16", 'home_team_score'=>"4", 'away_team_score'=>"0"),
    array('id'=>"17", 'home_team_score'=>"0", 'away_team_score'=>"2"),
    array('id'=>"18", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"19", 'home_team_score'=>"2", 'away_team_score'=>"6"),
    array('id'=>"20", 'home_team_score'=>"2", 'away_team_score'=>"0"),
    array('id'=>"21", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"22", 'home_team_score'=>"3", 'away_team_score'=>"1"),
    array('id'=>"23", 'home_team_score'=>"2", 'away_team_score'=>"3"),
    array('id'=>"24", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"25", 'home_team_score'=>"1", 'away_team_score'=>"2"),
    array('id'=>"26", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"27", 'home_team_score'=>"1", 'away_team_score'=>"3"),
    array('id'=>"28", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"29", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"30", 'home_team_score'=>"0", 'away_team_score'=>"3"),
    array('id'=>"31", 'home_team_score'=>"0", 'away_team_score'=>"3"),
    array('id'=>"32", 'home_team_score'=>"0", 'away_team_score'=>"0"),
    array('id'=>"33", 'home_team_score'=>"2", 'away_team_score'=>"2"),
    array('id'=>"34", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"35", 'home_team_score'=>"0", 'away_team_score'=>"1"),
    array('id'=>"36", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"37", 'home_team_score'=>"3", 'away_team_score'=>"2"),
    array('id'=>"38", 'home_team_score'=>"0", 'away_team_score'=>"1"),
    array('id'=>"39", 'home_team_score'=>"0", 'away_team_score'=>"1"),
    array('id'=>"40", 'home_team_score'=>"1", 'away_team_score'=>"2"),
    array('id'=>"41", 'home_team_score'=>"0", 'away_team_score'=>"3"),
    array('id'=>"42", 'home_team_score'=>"3", 'away_team_score'=>"1"),
    array('id'=>"43", 'home_team_score'=>"3", 'away_team_score'=>"1"),
    array('id'=>"44", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"45", 'home_team_score'=>"3", 'away_team_score'=>"0"),
    array('id'=>"46", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"47", 'home_team_score'=>"3", 'away_team_score'=>"1"),
    array('id'=>"48", 'home_team_score'=>"0", 'away_team_score'=>"0"),
    array('id'=>"49", 'home_team_score'=>"2", 'away_team_score'=>"2"),
    array('id'=>"50", 'home_team_score'=>"2", 'away_team_score'=>"2"),
    array('id'=>"51", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"52", 'home_team_score'=>"4", 'away_team_score'=>"2"),
    array('id'=>"53", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"54", 'home_team_score'=>"4", 'away_team_score'=>"2"),
    array('id'=>"55", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"56", 'home_team_score'=>"0", 'away_team_score'=>"1"),
    array('id'=>"57", 'home_team_score'=>"1", 'away_team_score'=>"2"),
    array('id'=>"58", 'home_team_score'=>"2", 'away_team_score'=>"2"),
    array('id'=>"59", 'home_team_score'=>"0", 'away_team_score'=>"3"),
    array('id'=>"60", 'home_team_score'=>"3", 'away_team_score'=>"1"),
    array('id'=>"61", 'home_team_score'=>"0", 'away_team_score'=>"1"),
    array('id'=>"62", 'home_team_score'=>"3", 'away_team_score'=>"1"),
    array('id'=>"63", 'home_team_score'=>"5", 'away_team_score'=>"3"),
    array('id'=>"64", 'home_team_score'=>"1", 'away_team_score'=>"0"),
    array('id'=>"65", 'home_team_score'=>"3", 'away_team_score'=>"2"),
    array('id'=>"66", 'home_team_score'=>"4", 'away_team_score'=>"1"),
    array('id'=>"67", 'home_team_score'=>"0", 'away_team_score'=>"0"),
    array('id'=>"68", 'home_team_score'=>"0", 'away_team_score'=>"0"),
    array('id'=>"69", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"70", 'home_team_score'=>"3", 'away_team_score'=>"2"),
    array('id'=>"71", 'home_team_score'=>"4", 'away_team_score'=>"1"),
    array('id'=>"72", 'home_team_score'=>"1", 'away_team_score'=>"3"),
    array('id'=>"73", 'home_team_score'=>"0", 'away_team_score'=>"2"),
    array('id'=>"74", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"75", 'home_team_score'=>"0", 'away_team_score'=>"1"),
    array('id'=>"76", 'home_team_score'=>"2", 'away_team_score'=>"3"),
    array('id'=>"77", 'home_team_score'=>"2", 'away_team_score'=>"0"),
    array('id'=>"78", 'home_team_score'=>"1", 'away_team_score'=>"2"),
    array('id'=>"79", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"80", 'home_team_score'=>"1", 'away_team_score'=>"0"),
    array('id'=>"81", 'home_team_score'=>"1", 'away_team_score'=>"3"),
    array('id'=>"82", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"83", 'home_team_score'=>"4", 'away_team_score'=>"3"),
    array('id'=>"84", 'home_team_score'=>"2", 'away_team_score'=>"2"),
    array('id'=>"85", 'home_team_score'=>"1", 'away_team_score'=>"0"),
    array('id'=>"86", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"87", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"88", 'home_team_score'=>"1", 'away_team_score'=>"0"),
    array('id'=>"89", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"90", 'home_team_score'=>"2", 'away_team_score'=>"2"),
    array('id'=>"91", 'home_team_score'=>"1", 'away_team_score'=>"0"),
    array('id'=>"92", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"93", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"94", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"95", 'home_team_score'=>"3", 'away_team_score'=>"0"),
    array('id'=>"96", 'home_team_score'=>"1", 'away_team_score'=>"0"),
    array('id'=>"97", 'home_team_score'=>"2", 'away_team_score'=>"2"),
    array('id'=>"98", 'home_team_score'=>"4", 'away_team_score'=>"1"),
    array('id'=>"99", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"100", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"101", 'home_team_score'=>"3", 'away_team_score'=>"2"),
    array('id'=>"102", 'home_team_score'=>"0", 'away_team_score'=>"2"),
    array('id'=>"103", 'home_team_score'=>"0", 'away_team_score'=>"0"),
    array('id'=>"104", 'home_team_score'=>"2", 'away_team_score'=>"0"),
    array('id'=>"105", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"106", 'home_team_score'=>"2", 'away_team_score'=>"0"),
    array('id'=>"107", 'home_team_score'=>"3", 'away_team_score'=>"0"),
    array('id'=>"108", 'home_team_score'=>"1", 'away_team_score'=>"3"),
    array('id'=>"109", 'home_team_score'=>"1", 'away_team_score'=>"2"),
    array('id'=>"110", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"111", 'home_team_score'=>"1", 'away_team_score'=>"2"),
    array('id'=>"112", 'home_team_score'=>"1", 'away_team_score'=>"2"),
    array('id'=>"113", 'home_team_score'=>"3", 'away_team_score'=>"0"),
    array('id'=>"114", 'home_team_score'=>"2", 'away_team_score'=>"2"),
    array('id'=>"115", 'home_team_score'=>"0", 'away_team_score'=>"0"),
    array('id'=>"116", 'home_team_score'=>"1", 'away_team_score'=>"4"),
    array('id'=>"117", 'home_team_score'=>"0", 'away_team_score'=>"4"),
    array('id'=>"118", 'home_team_score'=>"2", 'away_team_score'=>"3"),
    array('id'=>"119", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"120", 'home_team_score'=>"0", 'away_team_score'=>"2"),
    array('id'=>"121", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"122", 'home_team_score'=>"4", 'away_team_score'=>"1"),
    array('id'=>"123", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"124", 'home_team_score'=>"1", 'away_team_score'=>"0"),
    array('id'=>"125", 'home_team_score'=>"2", 'away_team_score'=>"4"),
    array('id'=>"126", 'home_team_score'=>"2", 'away_team_score'=>"5"),
    array('id'=>"127", 'home_team_score'=>"3", 'away_team_score'=>"0"),
    array('id'=>"128", 'home_team_score'=>"4", 'away_team_score'=>"0"),
    array('id'=>"129", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"130", 'home_team_score'=>"2", 'away_team_score'=>"0"),
    array('id'=>"131", 'home_team_score'=>"0", 'away_team_score'=>"1"),
    array('id'=>"132", 'home_team_score'=>"3", 'away_team_score'=>"1"),
    array('id'=>"133", 'home_team_score'=>"4", 'away_team_score'=>"0"),
    array('id'=>"134", 'home_team_score'=>"3", 'away_team_score'=>"0"),
    array('id'=>"135", 'home_team_score'=>"3", 'away_team_score'=>"3"),
    array('id'=>"136", 'home_team_score'=>"1", 'away_team_score'=>"5"),
    array('id'=>"137", 'home_team_score'=>"2", 'away_team_score'=>"0"),
    array('id'=>"138", 'home_team_score'=>"3", 'away_team_score'=>"1"),
    array('id'=>"139", 'home_team_score'=>"3", 'away_team_score'=>"1"),
    array('id'=>"140", 'home_team_score'=>"1", 'away_team_score'=>"0"),
    array('id'=>"141", 'home_team_score'=>"1", 'away_team_score'=>"0"),
    array('id'=>"142", 'home_team_score'=>"4", 'away_team_score'=>"2"),
    array('id'=>"143", 'home_team_score'=>"2", 'away_team_score'=>"2"),
    array('id'=>"144", 'home_team_score'=>"2", 'away_team_score'=>"3"),
    array('id'=>"145", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"146", 'home_team_score'=>"1", 'away_team_score'=>"2"),
    array('id'=>"147", 'home_team_score'=>"2", 'away_team_score'=>"2"),
    array('id'=>"148", 'home_team_score'=>"3", 'away_team_score'=>"4"),
    array('id'=>"149", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"150", 'home_team_score'=>"0", 'away_team_score'=>"0"),
    array('id'=>"151", 'home_team_score'=>"2", 'away_team_score'=>"2"),
    array('id'=>"152", 'home_team_score'=>"4", 'away_team_score'=>"0"),
    array('id'=>"153", 'home_team_score'=>"1", 'away_team_score'=>"2"),
    array('id'=>"154", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"155", 'home_team_score'=>"1", 'away_team_score'=>"3"),
    array('id'=>"156", 'home_team_score'=>"1", 'away_team_score'=>"2"),
    array('id'=>"157", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"158", 'home_team_score'=>"0", 'away_team_score'=>"5"),
    array('id'=>"159", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"160", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"161", 'home_team_score'=>"0", 'away_team_score'=>"2"),
    array('id'=>"162", 'home_team_score'=>"0", 'away_team_score'=>"4"),
    array('id'=>"163", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"164", 'home_team_score'=>"1", 'away_team_score'=>"5"),
    array('id'=>"165", 'home_team_score'=>"0", 'away_team_score'=>"0"),
    array('id'=>"166", 'home_team_score'=>"0", 'away_team_score'=>"0"),
    array('id'=>"167", 'home_team_score'=>"0", 'away_team_score'=>"3"),
    array('id'=>"168", 'home_team_score'=>"0", 'away_team_score'=>"3"),
    array('id'=>"169", 'home_team_score'=>"3", 'away_team_score'=>"6"),
    array('id'=>"170", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"171", 'home_team_score'=>"0", 'away_team_score'=>"0"),
    array('id'=>"172", 'home_team_score'=>"1", 'away_team_score'=>"2"),
    array('id'=>"173", 'home_team_score'=>"3", 'away_team_score'=>"0"),
    array('id'=>"174", 'home_team_score'=>"1", 'away_team_score'=>"0"),
    array('id'=>"175", 'home_team_score'=>"0", 'away_team_score'=>"1"),
    array('id'=>"176", 'home_team_score'=>"2", 'away_team_score'=>"0"),
    array('id'=>"177", 'home_team_score'=>"3", 'away_team_score'=>"1"),
    array('id'=>"178", 'home_team_score'=>"0", 'away_team_score'=>"0"),
    array('id'=>"179", 'home_team_score'=>"1", 'away_team_score'=>"0"),
    array('id'=>"180", 'home_team_score'=>"0", 'away_team_score'=>"2"),
    array('id'=>"181", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"182", 'home_team_score'=>"0", 'away_team_score'=>"2"),
    array('id'=>"183", 'home_team_score'=>"2", 'away_team_score'=>"2"),
    array('id'=>"184", 'home_team_score'=>"2", 'away_team_score'=>"2"),
    array('id'=>"185", 'home_team_score'=>"0", 'away_team_score'=>"5"),
    array('id'=>"186", 'home_team_score'=>"2", 'away_team_score'=>"2"),
    array('id'=>"187", 'home_team_score'=>"2", 'away_team_score'=>"0"),
    array('id'=>"188", 'home_team_score'=>"0", 'away_team_score'=>"2"),
    array('id'=>"189", 'home_team_score'=>"1", 'away_team_score'=>"3"),
    array('id'=>"190", 'home_team_score'=>"1", 'away_team_score'=>"2"),
    array('id'=>"191", 'home_team_score'=>"0", 'away_team_score'=>"5"),
    array('id'=>"192", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"193", 'home_team_score'=>"1", 'away_team_score'=>"0"),
    array('id'=>"194", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"195", 'home_team_score'=>"4", 'away_team_score'=>"1"),
    array('id'=>"196", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"197", 'home_team_score'=>"2", 'away_team_score'=>"2"),
    array('id'=>"198", 'home_team_score'=>"2", 'away_team_score'=>"2"),
    array('id'=>"199", 'home_team_score'=>"0", 'away_team_score'=>"3"),
    array('id'=>"200", 'home_team_score'=>"3", 'away_team_score'=>"2"),
    array('id'=>"201", 'home_team_score'=>"2", 'away_team_score'=>"2"),
    array('id'=>"202", 'home_team_score'=>"2", 'away_team_score'=>"2"),
    array('id'=>"203", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"204", 'home_team_score'=>"0", 'away_team_score'=>"1"),
    array('id'=>"205", 'home_team_score'=>"0", 'away_team_score'=>"2"),
    array('id'=>"206", 'home_team_score'=>"3", 'away_team_score'=>"0"),
    array('id'=>"207", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"208", 'home_team_score'=>"0", 'away_team_score'=>"2"),
    array('id'=>"209", 'home_team_score'=>"3", 'away_team_score'=>"1"),
    array('id'=>"210", 'home_team_score'=>"1", 'away_team_score'=>"4"),
    array('id'=>"211", 'home_team_score'=>"0", 'away_team_score'=>"2"),
    array('id'=>"212", 'home_team_score'=>"0", 'away_team_score'=>"2"),
    array('id'=>"213", 'home_team_score'=>"0", 'away_team_score'=>"2"),
    array('id'=>"214", 'home_team_score'=>"2", 'away_team_score'=>"2"),
    array('id'=>"215", 'home_team_score'=>"1", 'away_team_score'=>"3"),
    array('id'=>"216", 'home_team_score'=>"3", 'away_team_score'=>"2"),
    array('id'=>"217", 'home_team_score'=>"3", 'away_team_score'=>"2"),
    array('id'=>"218", 'home_team_score'=>"0", 'away_team_score'=>"6"),
    array('id'=>"219", 'home_team_score'=>"3", 'away_team_score'=>"1"),
    array('id'=>"220", 'home_team_score'=>"4", 'away_team_score'=>"1"),
    array('id'=>"221", 'home_team_score'=>"0", 'away_team_score'=>"1"),
    array('id'=>"222", 'home_team_score'=>"0", 'away_team_score'=>"1"),
    array('id'=>"223", 'home_team_score'=>"1", 'away_team_score'=>"3"),
    array('id'=>"224", 'home_team_score'=>"5", 'away_team_score'=>"0"),
    array('id'=>"225", 'home_team_score'=>"3", 'away_team_score'=>"1"),
    array('id'=>"226", 'home_team_score'=>"1", 'away_team_score'=>"2"),
    array('id'=>"227", 'home_team_score'=>"1", 'away_team_score'=>"2"),
    array('id'=>"228", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"229", 'home_team_score'=>"0", 'away_team_score'=>"1"),
    array('id'=>"230", 'home_team_score'=>"7", 'away_team_score'=>"0"),
    array('id'=>"231", 'home_team_score'=>"1", 'away_team_score'=>"2"),
    array('id'=>"232", 'home_team_score'=>"4", 'away_team_score'=>"0"),
    array('id'=>"233", 'home_team_score'=>"0", 'away_team_score'=>"2"),
    array('id'=>"234", 'home_team_score'=>"1", 'away_team_score'=>"2"),
    array('id'=>"235", 'home_team_score'=>"2", 'away_team_score'=>"0"),
    array('id'=>"236", 'home_team_score'=>"0", 'away_team_score'=>"2"),
    array('id'=>"237", 'home_team_score'=>"0", 'away_team_score'=>"2"),
    array('id'=>"238", 'home_team_score'=>"5", 'away_team_score'=>"1"),
    array('id'=>"239", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"240", 'home_team_score'=>"2", 'away_team_score'=>"2"),
    array('id'=>"241", 'home_team_score'=>"3", 'away_team_score'=>"0"),
    array('id'=>"242", 'home_team_score'=>"0", 'away_team_score'=>"2"),
    array('id'=>"243", 'home_team_score'=>"1", 'away_team_score'=>"3"),
    array('id'=>"244", 'home_team_score'=>"0", 'away_team_score'=>"1"),
    array('id'=>"245", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"246", 'home_team_score'=>"4", 'away_team_score'=>"0"),
    array('id'=>"247", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"248", 'home_team_score'=>"1", 'away_team_score'=>"2"),
    array('id'=>"249", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"250", 'home_team_score'=>"1", 'away_team_score'=>"0"),
    array('id'=>"251", 'home_team_score'=>"2", 'away_team_score'=>"2"),
    array('id'=>"252", 'home_team_score'=>"0", 'away_team_score'=>"4"),
    array('id'=>"253", 'home_team_score'=>"2", 'away_team_score'=>"2"),
    array('id'=>"254", 'home_team_score'=>"1", 'away_team_score'=>"4"),
    array('id'=>"255", 'home_team_score'=>"0", 'away_team_score'=>"2"),
    array('id'=>"256", 'home_team_score'=>"0", 'away_team_score'=>"1"),
    array('id'=>"257", 'home_team_score'=>"0", 'away_team_score'=>"1"),
    array('id'=>"258", 'home_team_score'=>"0", 'away_team_score'=>"4"),
    array('id'=>"259", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"260", 'home_team_score'=>"4", 'away_team_score'=>"3"),
    array('id'=>"261", 'home_team_score'=>"0", 'away_team_score'=>"2"),
    array('id'=>"262", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"263", 'home_team_score'=>"4", 'away_team_score'=>"1"),
    array('id'=>"264", 'home_team_score'=>"1", 'away_team_score'=>"2"),
    array('id'=>"265", 'home_team_score'=>"4", 'away_team_score'=>"0"),
    array('id'=>"266", 'home_team_score'=>"0", 'away_team_score'=>"0"),
    array('id'=>"267", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"268", 'home_team_score'=>"0", 'away_team_score'=>"1"),
    array('id'=>"269", 'home_team_score'=>"3", 'away_team_score'=>"2"),
    array('id'=>"270", 'home_team_score'=>"2", 'away_team_score'=>"0"),
    array('id'=>"271", 'home_team_score'=>"2", 'away_team_score'=>"0"),
    array('id'=>"272", 'home_team_score'=>"1", 'away_team_score'=>"0"),
    array('id'=>"273", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"274", 'home_team_score'=>"1", 'away_team_score'=>"0"),
    array('id'=>"275", 'home_team_score'=>"3", 'away_team_score'=>"1"),
    array('id'=>"276", 'home_team_score'=>"0", 'away_team_score'=>"1"),
    array('id'=>"277", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"278", 'home_team_score'=>"2", 'away_team_score'=>"2"),
    array('id'=>"279", 'home_team_score'=>"1", 'away_team_score'=>"0"),
    array('id'=>"280", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"281", 'home_team_score'=>"0", 'away_team_score'=>"1"),
    array('id'=>"282", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"283", 'home_team_score'=>"2", 'away_team_score'=>"4"),
    array('id'=>"284", 'home_team_score'=>"2", 'away_team_score'=>"2"),
    array('id'=>"285", 'home_team_score'=>"1", 'away_team_score'=>"2"),
    array('id'=>"286", 'home_team_score'=>"1", 'away_team_score'=>"2"),
    array('id'=>"287", 'home_team_score'=>"1", 'away_team_score'=>"0"),
    array('id'=>"288", 'home_team_score'=>"2", 'away_team_score'=>"0"),
    array('id'=>"289", 'home_team_score'=>"0", 'away_team_score'=>"3"),
    array('id'=>"290", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"291", 'home_team_score'=>"1", 'away_team_score'=>"0"),
    array('id'=>"292", 'home_team_score'=>"1", 'away_team_score'=>"0"),
    array('id'=>"293", 'home_team_score'=>"1", 'away_team_score'=>"2"),
    array('id'=>"294", 'home_team_score'=>"0", 'away_team_score'=>"3"),
    array('id'=>"295", 'home_team_score'=>"2", 'away_team_score'=>"0"),
    array('id'=>"296", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"297", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"298", 'home_team_score'=>"1", 'away_team_score'=>"0"),
    array('id'=>"299", 'home_team_score'=>"1", 'away_team_score'=>"0"),
    array('id'=>"300", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"301", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"302", 'home_team_score'=>"1", 'away_team_score'=>"2"),
    array('id'=>"303", 'home_team_score'=>"2", 'away_team_score'=>"2"),
    array('id'=>"304", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"305", 'home_team_score'=>"0", 'away_team_score'=>"0"),
    array('id'=>"306", 'home_team_score'=>"3", 'away_team_score'=>"2"),
    array('id'=>"307", 'home_team_score'=>"3", 'away_team_score'=>"1"),
    array('id'=>"308", 'home_team_score'=>"0", 'away_team_score'=>"0"),
    array('id'=>"309", 'home_team_score'=>"0", 'away_team_score'=>"3"),
    array('id'=>"310", 'home_team_score'=>"5", 'away_team_score'=>"2"),
    array('id'=>"311", 'home_team_score'=>"2", 'away_team_score'=>"2"),
    array('id'=>"312", 'home_team_score'=>"0", 'away_team_score'=>"1"),
    array('id'=>"313", 'home_team_score'=>"0", 'away_team_score'=>"3"),
    array('id'=>"314", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"315", 'home_team_score'=>"2", 'away_team_score'=>"2"),
    array('id'=>"316", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"317", 'home_team_score'=>"4", 'away_team_score'=>"2"),
    array('id'=>"318", 'home_team_score'=>"4", 'away_team_score'=>"1"),
    array('id'=>"319", 'home_team_score'=>"1", 'away_team_score'=>"0"),
    array('id'=>"320", 'home_team_score'=>"5", 'away_team_score'=>"0"),
    array('id'=>"321", 'home_team_score'=>"4", 'away_team_score'=>"2"),
    array('id'=>"322", 'home_team_score'=>"0", 'away_team_score'=>"0"),
    array('id'=>"323", 'home_team_score'=>"0", 'away_team_score'=>"2"),
    array('id'=>"324", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"325", 'home_team_score'=>"4", 'away_team_score'=>"1"),
    array('id'=>"326", 'home_team_score'=>"1", 'away_team_score'=>"2"),
    array('id'=>"327", 'home_team_score'=>"0", 'away_team_score'=>"4"),
    array('id'=>"328", 'home_team_score'=>"0", 'away_team_score'=>"1"),
    array('id'=>"329", 'home_team_score'=>"0", 'away_team_score'=>"1"),
    array('id'=>"330", 'home_team_score'=>"1", 'away_team_score'=>"2"),
    array('id'=>"331", 'home_team_score'=>"2", 'away_team_score'=>"1"),
    array('id'=>"332", 'home_team_score'=>"2", 'away_team_score'=>"2"),
    array('id'=>"333", 'home_team_score'=>"1", 'away_team_score'=>"0"),
    array('id'=>"334", 'home_team_score'=>"3", 'away_team_score'=>"2"),
    array('id'=>"335", 'home_team_score'=>"3", 'away_team_score'=>"0"),
    array('id'=>"336", 'home_team_score'=>"1", 'away_team_score'=>"2"),
    array('id'=>"337", 'home_team_score'=>"3", 'away_team_score'=>"0"),
    array('id'=>"338", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"339", 'home_team_score'=>"5", 'away_team_score'=>"1"),
    array('id'=>"340", 'home_team_score'=>"0", 'away_team_score'=>"2"),
    array('id'=>"341", 'home_team_score'=>"1", 'away_team_score'=>"0"),
    array('id'=>"342", 'home_team_score'=>"1", 'away_team_score'=>"0"),
    array('id'=>"343", 'home_team_score'=>"2", 'away_team_score'=>"2"),
    array('id'=>"344", 'home_team_score'=>"2", 'away_team_score'=>"0"),
    array('id'=>"345", 'home_team_score'=>"1", 'away_team_score'=>"2"),
    array('id'=>"346", 'home_team_score'=>"4", 'away_team_score'=>"3"),
    array('id'=>"347", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"348", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"349", 'home_team_score'=>"3", 'away_team_score'=>"1"),
    array('id'=>"350", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"351", 'home_team_score'=>"1", 'away_team_score'=>"3"),
    array('id'=>"352", 'home_team_score'=>"0", 'away_team_score'=>"1"),
    array('id'=>"353", 'home_team_score'=>"0", 'away_team_score'=>"0"),
    array('id'=>"354", 'home_team_score'=>"0", 'away_team_score'=>"2"),
    array('id'=>"355", 'home_team_score'=>"0", 'away_team_score'=>"1"),
    array('id'=>"356", 'home_team_score'=>"2", 'away_team_score'=>"0"),
    array('id'=>"357", 'home_team_score'=>"0", 'away_team_score'=>"2"),
    array('id'=>"358", 'home_team_score'=>"2", 'away_team_score'=>"2"),
    array('id'=>"359", 'home_team_score'=>"0", 'away_team_score'=>"2"),
    array('id'=>"360", 'home_team_score'=>"2", 'away_team_score'=>"2"),
    array('id'=>"361", 'home_team_score'=>"2", 'away_team_score'=>"0"),
    array('id'=>"362", 'home_team_score'=>"1", 'away_team_score'=>"0"),
    array('id'=>"363", 'home_team_score'=>"2", 'away_team_score'=>"0"),
    array('id'=>"364", 'home_team_score'=>"1", 'away_team_score'=>"2"),
    array('id'=>"365", 'home_team_score'=>"2", 'away_team_score'=>"3"),
    array('id'=>"366", 'home_team_score'=>"2", 'away_team_score'=>"0"),
    array('id'=>"367", 'home_team_score'=>"1", 'away_team_score'=>"0"),
    array('id'=>"368", 'home_team_score'=>"3", 'away_team_score'=>"2"),
    array('id'=>"369", 'home_team_score'=>"4", 'away_team_score'=>"2"),
    array('id'=>"370", 'home_team_score'=>"3", 'away_team_score'=>"1"),
    array('id'=>"371", 'home_team_score'=>"2", 'away_team_score'=>"0"),
    array('id'=>"372", 'home_team_score'=>"0", 'away_team_score'=>"2"),
    array('id'=>"373", 'home_team_score'=>"1", 'away_team_score'=>"3"),
    array('id'=>"374", 'home_team_score'=>"1", 'away_team_score'=>"1"),
    array('id'=>"375", 'home_team_score'=>"2", 'away_team_score'=>"0"),
    array('id'=>"376", 'home_team_score'=>"0", 'away_team_score'=>"1"),
    array('id'=>"377", 'home_team_score'=>"0", 'away_team_score'=>"1"),
    array('id'=>"378", 'home_team_score'=>"1", 'away_team_score'=>"2"),
    array('id'=>"379", 'home_team_score'=>"1", 'away_team_score'=>"4"),
    array('id'=>"380", 'home_team_score'=>"1", 'away_team_score'=>"1")
);


foreach ($results as $result) {
    $fix = App\Models\Fixture::findOrFail($result['id']);
    
    $fix->update([
        'home_team_score' => $result['home_team_score'], 
        'away_team_score' => $result['away_team_score']
    ]);
}

});
